import { PetPeriodOfLife, QuestionLanguage } from './pet-domain.types';

export interface QuestionDefinition {
  id: string;
  version: number;
  periodOfLife: PetPeriodOfLife;
  correctOptionId: string;
  content: Record<QuestionLanguage, {
    prompt: string;
    options: { id: string; text: string }[];
    explanation: string;
  }>;
}

type Choices = [string, string, string, string];
function question(
  id: string, periodOfLife: PetPeriodOfLife, correct: 1 | 2 | 3 | 4,
  ru: [string, Choices, string], en: [string, Choices, string]
): QuestionDefinition {
  const localize = ([prompt, options, explanation]: typeof ru) => ({
    prompt, options: options.map((text, index) => ({ id: `option-${index + 1}`, text })), explanation
  });
  return { id, version: 1, periodOfLife, correctOptionId: `option-${correct}`, content: { ru: localize(ru), en: localize(en) } };
}

// Each attempt saves a copy, so later edits cannot change a question already issued.
export const QUESTION_CATALOG: readonly QuestionDefinition[] = [
  question('child-berries', 'child', 3,
    ['У меня две ягоды. Я нашёл ещё одну. Сколько теперь?', ['Одна', 'Две', 'Три', 'Четыре'], 'Две ягоды и ещё одна — всего три.'],
    ['I have two berries and find one more. How many do I have now?', ['One', 'Two', 'Three', 'Four'], 'Two berries plus one berry make three.']),
  question('child-shape', 'child', 2,
    ['Какая фигура совсем без углов?', ['Квадрат', 'Круг', 'Треугольник', 'Прямоугольник'], 'У круга нет углов.'],
    ['Which shape has no corners?', ['Square', 'Circle', 'Triangle', 'Rectangle'], 'A circle has no corners.']),
  question('child-ice', 'child', 4,
    ['Кусочек льда растаял в тёплой миске. Что получилось?', ['Камень', 'Песок', 'Соль', 'Вода'], 'Лёд — это замёрзшая вода. При таянии он снова становится водой.'],
    ['An ice cube melts in a warm bowl. What does it become?', ['Stone', 'Sand', 'Salt', 'Water'], 'Ice is frozen water. When it melts, it becomes liquid water again.']),
  question('child-sequence', 'child', 1,
    ['Бусины идут так: красная, синяя, красная, синяя. Какая следующая, если узор повторяется?', ['Красная', 'Синяя', 'Зелёная', 'Жёлтая'], 'Красная и синяя чередуются. После синей снова идёт красная.'],
    ['The beads go red, blue, red, blue. Which comes next if the pattern repeats?', ['Red', 'Blue', 'Green', 'Yellow'], 'Red and blue alternate, so red follows blue.']),
  question('child-leaves', 'child', 2,
    ['На ветке было пять листьев. Два упали. Сколько осталось на ветке?', ['Два', 'Три', 'Четыре', 'Пять'], 'Из пяти листьев убираем два: остаётся три.'],
    ['A branch has five leaves. Two fall off. How many are left on the branch?', ['Two', 'Three', 'Four', 'Five'], 'Subtract two fallen leaves from five, and three remain.']),
  question('child-triangle', 'child', 4,
    ['Сколько углов у треугольника?', ['Один', 'Два', 'Четыре', 'Три'], 'У треугольника три стороны и три угла.'],
    ['How many corners does a triangle have?', ['One', 'Two', 'Four', 'Three'], 'A triangle has three sides and three corners.']),
  question('child-hearing', 'child', 1,
    ['Колокольчик зазвенел. Чем человек слышит его звон?', ['Ушами', 'Глазами', 'Носом', 'Языком'], 'Уши помогают слышать звуки, в том числе звон колокольчика.'],
    ['A little bell rings. Which body part do people use to hear it?', ['Ears', 'Eyes', 'Nose', 'Tongue'], 'Our ears help us hear sounds, including a ringing bell.']),
  question('child-cups', 'child', 3,
    ['Четыре одинаковые чашки наполнены по-разному. В какой больше всего воды?', ['В пустой', 'В заполненной наполовину', 'В полной', 'В заполненной на четверть'], 'В полной чашке больше воды, чем в такой же чашке, наполненной лишь частично.'],
    ['Four identical cups hold different amounts of water. Which holds the most?', ['The empty cup', 'The half-full cup', 'The full cup', 'The quarter-full cup'], 'A full cup holds more water than an identical cup that is only partly full.']),
  question('child-acorn', 'child', 2,
    ['Что может вырасти из жёлудя, если ему хватает воды, света и места?', ['Сосна', 'Дуб', 'Берёза', 'Яблоня'], 'Жёлудь содержит семя дуба. Из него может вырасти новый дуб.'],
    ['What can grow from an acorn with enough water, light and space?', ['A pine tree', 'An oak tree', 'A birch tree', 'An apple tree'], 'An acorn contains an oak seed. It can grow into a new oak tree.']),
  question('child-arrival', 'child', 4,
    ['Белка пришла к домику раньше ежа. Кто из них пришёл первым?', ['Ёж', 'Они пришли одновременно', 'Нельзя узнать', 'Белка'], 'Раньше означает первым из этих двух гостей. Это белка.'],
    ['A squirrel reaches the cottage before a hedgehog. Which of them arrives first?', ['The hedgehog', 'They arrive together', 'We cannot tell', 'The squirrel'], 'Before means earlier than the other guest, so the squirrel arrives first.']),
  question('child-feathers', 'child', 1,
    ['Чем покрыто тело воробья?', ['Перьями', 'Шерстью', 'Панцирем', 'Иголками'], 'Воробей — птица. Его тело покрыто перьями.'],
    ['What covers a sparrow’s body?', ['Feathers', 'Fur', 'A shell', 'Spines'], 'A sparrow is a bird. Its body is covered with feathers.']),
  question('child-pairs', 'child', 3,
    ['У меня четыре варежки. В каждой паре две варежки. Сколько пар можно составить?', ['Одну', 'Три', 'Две', 'Четыре'], 'Четыре варежки делим на группы по две: получаются две пары.'],
    ['I have four mittens. Each pair has two mittens. How many pairs can I make?', ['One', 'Three', 'Two', 'Four'], 'Four mittens split into groups of two make two pairs.']),
  question('teen-ribbons', 'teen', 3,
    ['Красная лента длиннее синей, а синяя длиннее зелёной. Какая самая короткая?', ['Красная', 'Синяя', 'Зелёная', 'Все одинаковые'], 'Зелёная короче синей, а синяя короче красной.'],
    ['The red ribbon is longer than the blue one, and the blue is longer than the green. Which is shortest?', ['Red', 'Blue', 'Green', 'They are equal'], 'Green is shorter than blue, and blue is shorter than red.']),
  question('teen-berries', 'teen', 1,
    ['У меня три корзинки по две ягоды. Две ягоды я отдал другу. Сколько осталось?', ['Четыре', 'Две', 'Шесть', 'Восемь'], 'В трёх корзинках шесть ягод. Шесть минус две — четыре.'],
    ['I have three baskets with two berries each. I give two berries to a friend. How many remain?', ['Four', 'Two', 'Six', 'Eight'], 'Three baskets hold six berries. Six minus two is four.']),
  question('teen-shadow', 'teen', 2,
    ['Фонарь стоит слева от непрозрачного камня. В какую сторону от камня падает тень на землю?', ['К фонарю, влево', 'От фонаря, вправо', 'В обе стороны одинаково', 'Тени не будет'], 'Камень перекрывает свет, поэтому тень находится с противоположной от фонаря стороны.'],
    ['A lamp stands to the left of an opaque rock. In which direction does the rock cast its shadow on the ground?', ['Toward the lamp, left', 'Away from the lamp, right', 'Equally in both directions', 'There is no shadow'], 'The rock blocks the light, so its shadow falls on the side opposite the lamp.']),
  question('teen-days', 'teen', 4,
    ['Вчера был понедельник. Какой день будет послезавтра?', ['Вторник', 'Среда', 'Пятница', 'Четверг'], 'Сегодня вторник, завтра среда, а послезавтра четверг.'],
    ['Yesterday was Monday. What day is the day after tomorrow?', ['Tuesday', 'Wednesday', 'Friday', 'Thursday'], 'Today is Tuesday, tomorrow is Wednesday, and the day after is Thursday.']),
  question('teen-jugs', 'teen', 4,
    ['Я трижды налил в пустое ведро по два литра воды, а потом вылил один литр. Сколько воды осталось?', ['Три литра', 'Четыре литра', 'Шесть литров', 'Пять литров'], 'Три раза по два — шесть литров. Выливаем один: остаётся пять.'],
    ['I pour two litres of water into an empty bucket three times, then pour one litre out. How much remains?', ['Three litres', 'Four litres', 'Six litres', 'Five litres'], 'Three lots of two make six litres. Pouring out one leaves five.']),
  question('teen-map', 'teen', 1,
    ['На карте верх — север, право — восток. От домика я прошёл одну клетку вверх и одну вправо. Где я относительно домика?', ['К северо-востоку', 'К северо-западу', 'К юго-востоку', 'К юго-западу'], 'Шаг вверх ведёт на север, шаг вправо — на восток. Вместе это северо-восток от домика.'],
    ['On a map, up is north and right is east. From the cottage I move one square up and one right. Where am I relative to the cottage?', ['Northeast', 'Northwest', 'Southeast', 'Southwest'], 'Moving up takes you north, and moving right takes you east. Together they put you northeast of the cottage.']),
  question('teen-evaporation', 'teen', 3,
    ['В открытом блюдце за день стало меньше воды. Её никто не пил и не проливал, блюдце не протекает. Куда ушла часть воды?', ['Вся превратилась в лёд', 'Превратилась в песок', 'Испарилась в воздух', 'Превратилась в стекло'], 'Вода может испаряться: переходить в воздух в виде водяного пара, даже без кипения.'],
    ['An open saucer holds less water after a day. Nobody drinks or spills it, and the saucer does not leak. Where did some of the water go?', ['It all froze', 'It became sand', 'It evaporated into the air', 'It became glass'], 'Water can evaporate into the air as water vapour, even without boiling.']),
  question('teen-tracks', 'teen', 2,
    ['Я намочил лапы и иду по сухой дорожке, не наступая в новые лужи. Водяные следы становятся всё слабее. Почему?', ['На лапах становится больше воды', 'На лапах остаётся всё меньше воды', 'Дорожка превращается в воду', 'Лапы каждый раз становятся больше'],
      'При каждом шаге часть воды остаётся на дорожке. На лапах её всё меньше, поэтому следы слабее.'],
    ['My paws are wet. I walk along a dry path without stepping in any more puddles. My wet footprints get fainter. Why?', ['My paws hold more water', 'Less water remains on my paws', 'The path turns into water', 'My paws grow with every step'],
      'Each step leaves some water on the path. Less remains on my paws, so the footprints get fainter.']),
  question('teen-magnet', 'teen', 4,
    ['За тонким картоном лежит железная скрепка. Какой предмет может притянуть её через картон?', ['Деревянная ложка', 'Стеклянный шарик', 'Резиновый мяч', 'Магнит'], 'Магнит притягивает железо и может действовать через тонкий немагнитный картон.'],
    ['An iron paper clip lies behind a thin piece of cardboard. Which object can attract it through the cardboard?', ['A wooden spoon', 'A glass marble', 'A rubber ball', 'A magnet'], 'A magnet attracts iron and can act through thin, non-magnetic cardboard.']),
  question('teen-seedlings', 'teen', 1,
    ['Два одинаковых ростка стоят рядом в одинаковых горшках с одной почвой. Один поливают каждый день, другой не поливают. Какое условие различается?', ['Полив', 'Место', 'Размер горшка', 'Вид почвы'], 'По условию место, горшки и почва одинаковые. Различается только полив.'],
    ['Two identical seedlings stand together in identical pots with the same soil. One is watered daily; the other is not watered. Which condition differs?', ['Watering', 'Location', 'Pot size', 'Soil type'], 'The location, pots and soil are the same. Only the watering differs.']),
  question('teen-number-pattern', 'teen', 3,
    ['На камнях числа: 2, 5, 8, 11. Каждое следующее на три больше предыдущего. Какое число будет через два шага после 11?', ['14', '16', '17', '20'], 'Первый шаг: 11 + 3 = 14. Второй шаг: 14 + 3 = 17.'],
    ['The stones show 2, 5, 8, 11. Each number is three greater than the one before it. What number comes two steps after 11?', ['14', '16', '17', '20'], 'The first step is 11 + 3 = 14. The second is 14 + 3 = 17.']),
  question('teen-sharing', 'teen', 2,
    ['У меня 14 ягод. Я дал каждому из трёх друзей по четыре. Сколько ягод осталось у меня?', ['Одну', 'Две', 'Три', 'Четыре'], 'Трое друзей получили 3 × 4 = 12 ягод. У меня осталось 14 − 12 = 2.'],
    ['I have 14 berries and give four to each of three friends. How many do I have left?', ['One', 'Two', 'Three', 'Four'], 'The three friends receive 3 × 4 = 12 berries. I have 14 − 12 = 2 left.']),
  question('adult-shelf', 'adult', 1,
    ['На трёх местах стоят книга, фонарь и ключ. Книга левее ключа, фонарь не на краю. Какой порядок слева направо подходит?', ['Книга, фонарь, ключ', 'Ключ, фонарь, книга', 'Фонарь, книга, ключ', 'Книга, ключ, фонарь'], 'Фонарь должен стоять посередине. Книга левее ключа, значит книга первая, ключ последний.'],
    ['A book, a lamp and a key occupy three spaces. The book is left of the key; the lamp is not at an end. Which left-to-right order fits?', ['Book, lamp, key', 'Key, lamp, book', 'Lamp, book, key', 'Book, key, lamp'], 'The lamp must be in the middle. The book is left of the key, so the book comes first and the key last.']),
  question('adult-path', 'adult', 4,
    ['До озера через лес идти 12 минут, обратно по мосту — на 5 минут меньше. Я провёл у озера 8 минут. Сколько заняла вся прогулка?', ['19 минут', '20 минут', '32 минуты', '27 минут'], 'Обратный путь занимает 12 − 5 = 7 минут. Вся прогулка: 12 + 8 + 7 = 27 минут.'],
    ['It takes 12 minutes to reach the lake through the woods. The return via a bridge takes 5 minutes less. I spend 8 minutes at the lake. How long is the whole outing?', ['19 minutes', '20 minutes', '32 minutes', '27 minutes'], 'The return takes 12 − 5 = 7 minutes. The total is 12 + 8 + 7 = 27 minutes.']),
  question('adult-bags', 'adult', 2,
    ['В мешке три красных и три синих шарика. Сколько нужно взять не глядя, чтобы точно получить хотя бы два одного цвета?', ['Два', 'Три', 'Четыре', 'Шесть'], 'Первые два могут быть разных цветов. Третий обязательно совпадёт по цвету с одним из них.'],
    ['A bag holds three red and three blue balls. How many must you take without looking to guarantee at least two of the same colour?', ['Two', 'Three', 'Four', 'Six'], 'The first two may have different colours. The third must match one of them.']),
  question('adult-order', 'adult', 3,
    ['Аня пришла раньше Бори. Вера — позже Бори, но раньше Глеба. Кто пришёл вторым?', ['Аня', 'Вера', 'Боря', 'Глеб'], 'Единственный подходящий порядок: Аня, Боря, Вера, Глеб. Вторым пришёл Боря.'],
    ['Anna arrives before Ben. Vera arrives after Ben but before Glen. Who arrives second?', ['Anna', 'Vera', 'Ben', 'Glen'], 'The only possible order is Anna, Ben, Vera, Glen. Ben arrives second.']),
  question('adult-trails', 'adult', 2,
    ['К домику ведут три пути: через мост — 10 минут, через луг — два участка по 8 минут, через лес — 12 и 6 минут. Мост закрыт. Каков самый быстрый доступный путь?', ['Мост, 10 минут', 'Луг, 16 минут', 'Лес, 18 минут', 'Луг, 8 минут'],
      'Мост недоступен. Через луг идти 8 + 8 = 16 минут, через лес — 12 + 6 = 18. Луг быстрее.'],
    ['Three routes lead to the cottage: a bridge takes 10 minutes, a meadow has two 8-minute sections, and a forest has 12- and 6-minute sections. The bridge is closed. Which available route is fastest?', ['Bridge, 10 minutes', 'Meadow, 16 minutes', 'Forest, 18 minutes', 'Meadow, 8 minutes'],
      'The bridge is unavailable. The meadow takes 8 + 8 = 16 minutes; the forest takes 12 + 6 = 18. The meadow is faster.']),
  question('adult-labels', 'adult', 3,
    ['В трёх коробках шарики: только красные, только синие и смесь. Все три надписи неверны. Из коробки с надписью «Смесь» достали красный шарик. Что в этой коробке?', ['Смесь', 'Только синие', 'Только красные', 'Нельзя определить'],
      'Это не смесь, потому что надпись неверна. Красный шарик исключает коробку только с синими. Значит, здесь только красные.'],
    ['Three boxes contain only red balls, only blue balls, and a mixture. All three labels are wrong. A red ball is drawn from the box labelled “Mixture”. What does that box contain?', ['A mixture', 'Only blue balls', 'Only red balls', 'We cannot tell'],
      'It cannot contain a mixture because its label is wrong. The red ball rules out only blue balls, so it contains only red balls.']),
  question('adult-watering', 'adult', 4,
    ['Хочу узнать, влияет ли частота полива на рост одинаковых растений. В каком опыте меняется только частота полива?', ['Разные почвы и полив', 'Разные горшки и полив', 'Разное освещение и полив', 'Одинаковые почва, свет и горшки; разный полив'],
      'Чтобы сравнить влияние частоты полива, остальные условия сохраняют одинаковыми. Иначе причину различий не отделить.'],
    ['I want to find out whether watering frequency affects the growth of identical plants. Which experiment changes only watering frequency?', ['Different soils and watering', 'Different pots and watering', 'Different light and watering', 'Same soil, light and pots; different watering'],
      'To compare watering frequency, keep the other conditions the same. Otherwise, you cannot separate the possible causes of a difference.']),
  question('adult-code', 'adult', 1,
    ['Код состоит из цифр 1, 2 и 3, каждая используется один раз. Первая цифра вдвое больше последней. Какой это код?', ['231', '213', '312', '132'], 'Только 2 вдвое больше 1. Значит, 2 стоит первой, 1 — последней, а оставшаяся 3 — посередине.'],
    ['A code uses the digits 1, 2 and 3 exactly once each. The first digit is twice the last digit. What is the code?', ['231', '213', '312', '132'], 'Only 2 is twice 1. So 2 comes first, 1 comes last, and the remaining digit, 3, goes in the middle.']),
  question('adult-departure', 'adult', 2,
    ['Автобус уходит каждые 20 минут начиная с 09:00. Сейчас 09:37, до остановки идти 8 минут. На какой ближайший автобус я успею?', ['09:40', '10:00', '09:45', '10:20'], 'Я приду в 09:45. Автобус в 09:40 уже уедет, а следующий по расписанию — в 10:00.'],
    ['A bus leaves every 20 minutes starting at 09:00. It is now 09:37, and the stop is an 8-minute walk away. What is the next bus I can catch?', ['09:40', '10:00', '09:45', '10:20'], 'I will arrive at 09:45. The 09:40 bus will have left, and the next scheduled bus is at 10:00.']),
  question('adult-lanterns', 'adult', 3,
    ['Из красного, зелёного и синего фонарей горят ровно два. Зелёный и синий в одинаковом состоянии. Красный и зелёный — в разных. Какие горят?', ['Красный и зелёный', 'Красный и синий', 'Зелёный и синий', 'Все три'],
      'Зелёный и синий либо оба горят, либо оба выключены. Если оба выключены, двух горящих не получится. Значит, горят они, а красный выключен.'],
    ['Exactly two of the red, green and blue lanterns are lit. Green and blue are in the same state. Red and green are in different states. Which are lit?', ['Red and green', 'Red and blue', 'Green and blue', 'All three'],
      'Green and blue are either both on or both off. If both were off, there could not be two lit lanterns. So green and blue are on, and red is off.']),
  question('adult-insulation', 'adult', 4,
    ['В комнате 15 °C. В две одинаковые закрытые чашки налили поровну воды при 60 °C и по-разному утеплили. Через час в первой 25 °C, во второй 40 °C. Где вода потеряла меньше тепла, если её не подогревали?', ['В первой: она холоднее', 'В обеих одинаково', 'Нельзя сравнить температуры', 'Во второй: она остыла меньше'],
      'При одинаковых количестве воды и начальной температуре меньшему остыванию соответствует меньшая потеря тепла. Вторая остыла на 20 °C, первая — на 35 °C.'],
    ['A room is at 15 °C. Two identical closed cups get equal amounts of water at 60 °C and different insulation. After an hour, the first is at 25 °C and the second at 40 °C. Where did the water lose less heat if neither was reheated?', ['In the first: it is colder', 'In both equally', 'The temperatures cannot be compared', 'In the second: it cooled less'],
      'With equal amounts of water and the same starting temperature, less cooling means less heat lost. The second cooled by 20 °C; the first by 35 °C.']),
  question('adult-garden', 'adult', 1,
    ['Для растения нужно не меньше 6 часов солнца и защита от ветра. У стены — 7 часов и защита, на холме — 8 часов без защиты, под деревом — 3 часа и защита. Какое место подходит?', ['У стены', 'На холме', 'Под деревом', 'Все три места'],
      'У стены выполнены оба условия. На холме нет защиты от ветра, а под деревом слишком мало солнца.'],
    ['A plant needs at least 6 hours of sun and shelter from wind. A wall offers 7 hours and shelter, a hill offers 8 hours without shelter, and a tree offers 3 hours and shelter. Which place fits?', ['By the wall', 'On the hill', 'Under the tree', 'All three places'],
      'The wall meets both conditions. The hill lacks shelter from wind, and the tree provides too little sun.'])
];
